### ISSUE TITLE
Build all components

### ISSUE THREAD

**Issue by jonthomp** [jonthomp/react-tabler-components#3]
- [x] Avatar
- [x] Badge
- [x] Button
- [x] Basic Card
- [ ] Card Footer
- [ ] Pricing Card
- [ ] Chart Card
- [ ] Store Card
- [ ] Gallery Card
- [ ] Blog Card
- [x] Container
- [x] Dropdown
- [x] Form
- [x] Grid
- [x] Header
- [x] Icon
- [ ] Nav
- [x] Page
- [x] Page/Website header
- [ ] Page/Website navbar
- [ ] Page/Website footer
- [x] Table
- [x] Text
- [ ] Map
- [x] Alert
- [x] Progress
- [ ] Stamp

**Comment by iamzjohn** [comment]
Any Help needed?

**Comment by jonthomp** [comment]
@iamzjohn yeah totally thanks! Jump in on anything, just let me know what so we don't duplicate, and try to follow the same style/principles I've been using (although I'm happy to hear any suggestions/recommendations on changing things!).

I'm currently working on the Buttons and Forms components/docs.

**Comment by iamzjohn** [comment]
Okay, any thing I'll tell when I start

**Comment by iamzjohn** [comment]
I'll be working on the card footer,

**Comment by jonthomp** [comment]
@iamzjohn thanks for your help on these, just to let you know I am currently working on merging this repository into the new and official Tabler react repository you can find it here https://github.com/tabler/tabler-react.

It's nearly up to date with the work we were doing here, as soon as it is, would be good to have you come and join us over there to get involved :)

**Comment by iamzjohn** [comment]
Thanks @jonthomp, I will subscribe my self and help when possible. But I would like to know if I must stop, cuz I can see that the coding style isin't the same. So do I wait for the merge or I can continue and then can also be merged?

**Comment by jonthomp** [comment]
@iamzjohn awesome, hope you get involved. The main thing that has changed is moving away from PropTypes to flow instead. Everything else should be pretty much the same so I would say continue as you are and then we can merge later. I'll be merging your card footer PR I accepted into the new repository too

**Comment by iamzjohn** [comment]
@jonthomp I prefer to wait, and help when the merging end, it looks almost done. And then would be better do not duplicate work merging them.

**Comment by jonthomp** [comment]
@iamzjohn ok cool, all the components are now up to date, I haven't merged your footer in case you just want to go ahead and add it in to the new repository yourself?

**Comment by iamzjohn** [comment]
@jonthomp it's a great opportunity to have  a commit
